# 配合 course/10-5-原型與方法.md
(defn show [x] (print (string/format "%j" x)))

(print "== 方法呼叫語法 ==")
(def dog @{:name "Rex" :speak (fn [self] (string (self :name) " woof"))})
(show (:speak dog))
(show ((get dog :speak) dog))

(print "== 原型 ==")
(def Animal @{:speak (fn [self] (string (self :name) " makes a sound"))
              :intro (fn [self] (string "I am " (self :name)))})
(defn animal [name] (table/setproto @{:name name} Animal))
(def cat (animal "Tom"))
(show (:intro cat))
(show (:speak cat))
(show (keys cat))
(show (type (get cat :speak)))
(show (table/rawget cat :speak))

(def Dog (table/setproto @{:speak (fn [self] (string (self :name) " woof"))} Animal))
(def d (table/setproto @{:name "Rex"} Dog))
(show (:speak d))
(show (:intro d))

(def counter @{:n 0 :bump (fn [self] (put self :n (+ (self :n) 1)) (self :n))})
(show (:bump counter))
(show (:bump counter))

(print "== 有 :close 就能配 with ==")
(def Conn @{:close (fn [self] (print "closed"))
            :query (fn [self q] (string "ran " q))})
(defn connect [] (table/setproto @{:host "x"} Conn))
(show (with [c (connect)] (:query c "select 1")))
(show (try (with [c (connect)] (error "boom")) ([e] (string "caught " e))))

(print "== 坑：(:port cfg) 不是取值 ==")
(def cfg {:port 4000})
(show (cfg :port))
(show (:port cfg))
(show (4000 cfg))

(print "== 坑：忘了 self ==")
(def bad @{:inc (fn [n] (+ n 1))})
(show (protect (:inc bad 5)))

(print "== 坑：原型上的可變預設值是共用的 ==")
(def Bad @{:items @[]})
(def a1 (table/setproto @{} Bad))
(def a2 (table/setproto @{} Bad))
(array/push (a1 :items) 1)
(show (a2 :items))
(def Good @{:new (fn [self] (table/setproto @{:items @[]} self))})
(def g1 (:new Good))
(def g2 (:new Good))
(array/push (g1 :items) 1)
(show (g2 :items))

# ---- 練習解答 ----
(print "== 練習解答 ==")
# 1. Stack
(def Stack @{:push (fn [self x] (array/push (self :items) x) self)
             :pop (fn [self] (array/pop (self :items)))
             :size (fn [self] (length (self :items)))})
(defn stack [] (table/setproto @{:items @[]} Stack))
(def s (stack))
(:push s 1)
(:push s 2)
(show (:size s))
(show (:pop s))
(show (:size s))
# 2. Shape / Circle
(def Shape @{:describe (fn [self] (string (self :kind) " area " (:area self)))
             :area (fn [self] 0)})
(def Circle (table/setproto @{:area (fn [self] (* 3 (self :r) (self :r)))} Shape))
(def c (table/setproto @{:kind "circle" :r 2} Circle))
(show (:describe c))
