# 配合 docs/43、43b、43c（從 C／C++ 過來的逐條對照）
#
#   janet examples/compare-c.janet
#
# 每列印「C 的寫法 → Janet 的寫法 → 實際結果」。挑的是最容易憑 C 直覺寫錯的那些。

(defn 節 [t] (print "\n── " t " ─────────────────────"))
(defn 顯示 [r] (if (string? r) (string "\"" r "\"") (string/format "%j" r)))   # 字串直接印，%j 會把中文逃逸
(defn 列 [c j r] (printf "  %-34s %-40s => %s" c j (顯示 r)))
(defn 錯 [f] (try (do (f) :沒報錯) ([e] (string "錯：" e))))

(節 "數字：全部是 double")
(列 "7 / 2" "(/ 7 2)" (/ 7 2))
(列 "7 / 2  （整數除）" "(div 7 2)" (div 7 2))
(列 "-7 % 2" "(% -7 2)" (% -7 2))
(列 "（數學上的 mod）" "(mod -7 2)" (mod -7 2))
(列 "3 == 3.0" "(= 3 3.0)" (= 3 3.0))
(列 "2^53 + 1" "(+ 9007199254740992 1)" (+ 9007199254740992 1))
(列 "(int64_t)2^53 + 1" "(int/s64 …)" (string (+ (int/s64 9007199254740992) 1)))
(列 "printf(\"%d\", 3.5)  UB" "(string/format \"%d\" 3.5)" (錯 |(string/format "%d" 3.5)))

(節 "字串：string 不可變、buffer 可變")
(列 "printf(\"%3d|%-3d|%05.1f|%x\")" "(string/format 同名動詞 …)"
    (string/format "%3d|%-3d|%05.1f|%x" 42 42 3.14159 255))
(列 "strcat / sprintf" "(string \"a\" 1 :k 2.5)" (string "a" 1 :k 2.5))
(列 "strcpy 進緩衝" "(buffer/push @\"ab\" \"cd\")" (buffer/push @"ab" "cd"))
(列 "strlen(\"中\")" "(length \"中\")  ⚠ byte 數" (length "中"))
(列 "s[0]" "(get \"abc\" 0)  ⚠ 拿到 byte" (get "abc" 0))
(列 "'A'" "(chr \"A\")" (chr "A"))
(列 "s[0] = 'X'  對 string" "(put \"abc\" 0 65)" (錯 |(put "abc" 0 65)))
(列 "s[0] = 'X'  對 buffer" "(put @\"abc\" 0 (chr \"X\"))" (put @"abc" 0 (chr "X")))

(節 "陣列與 struct")
(列 "int a[5] = {0};" "(array/new-filled 5 0)" (array/new-filled 5 0))
(列 "⚠ 不是這個" "(length (array/new 5))  只是預留容量" (length (array/new 5)))
(列 "a[5] 越界" "(get @[1 2 3] 5)" (get @[1 2 3] 5))
(列 "a[5] 越界（要報錯版）" "(in @[1 2 3] 5)" (錯 |(in @[1 2 3] 5)))
(def p {:x 1 :y 2})
(列 "p.x" "(get p :x) / (p :x)" [(get p :x) (p :x)])
(列 "⚠ 不是這個" "(:x p)  這是呼叫方法" (:x p))
(列 "改 const struct" "(put {:x 1} :x 2)" (錯 |(put {:x 1} :x 2)))

(節 "指標：沒有，傳的本來就是參考")
(defn bump! [t] (put t :n (inc (get t :n))))
(def counter @{:n 0})
(bump! counter)
(列 "void bump(T *t){t->n++;}" "(defn bump! [t] (put t :n (inc (get t :n))))" counter)
(列 "NULL->x" "(put nil :a 1)" (錯 |(put nil :a 1)))

(節 "控制流")
(defn sw [x] (case x 1 :one 2 :two :other))
(列 "switch(x){case 1:…default:…}" "(case x 1 :one 2 :two :other)" (map sw [1 2 9]))
(列 "for (i=0;i<10;i+=3)" "(seq [i :range [0 10 3]] i)" (seq [i :range [0 10 3]] i))
(列 "for (i=5;i>0;i--)" "(seq [i :down [5 0]] i)" (seq [i :down [5 0]] i))
(列 "⚠ 負步長寫在 :range" "(seq [i :range [5 0 -1]] i)  靜默回空" (seq [i :range [5 0 -1]] i))
(def r @[])
(forv i 0 10 (array/push r i) (+= i 2))
(列 "for 裡改 i" "(forv i 0 10 … (+= i 2))" r)
(var i 10) (def dw @[])
(while true (array/push dw i) (++ i) (unless (< i 3) (break)))
(列 "do { … } while (i < 3)" "(while true … (unless (< i 3) (break)))" dw)
(列 "c ? a : b" "(if (> 5 3) :大 :小)" (if (> 5 3) :大 :小))
(列 "x ? x : d  當 x=0" "(or 0 :預設)  ⚠ 0 是真" (or 0 :預設))

(節 "位元：32 位元、名字不是符號")
(列 "6 & 3, 6 | 3, 6 ^ 3, ~0" "(band) (bor) (bxor) (bnot)" [(band 6 3) (bor 6 3) (bxor 6 3) (bnot 0)])
(列 "-16 >> 2（算術）" "(brshift -16 2)" (brshift -16 2))
(列 "(unsigned)-16 >> 2" "(brushift -16 2)" (錯 |(brushift -16 2)))
(列 "0xFFFFFFF0u >> 2" "(brushift 0xFFFFFFF0 2)" (brushift 0xFFFFFFF0 2))
(列 "1 << 33" "(blshift 1 33)  ⚠ 位移量 mod 32" (blshift 1 33))

(節 "enum、callback、可變參數、預設參數、static")
(def 顏色 [:red :green :blue])
(列 "enum {RED, GREEN, BLUE}; GREEN" "(index-of :green 顏色)" (index-of :green 顏色))
(defn twice [f x] (f (f x)))
(列 "int (*f)(int); twice(inc, 3)" "(twice inc 3)" (twice inc 3))
(defn sum [& xs] (+ ;xs))
(列 "va_list 加總" "(defn sum [& xs] (+ ;xs))" [(sum 1 2 3) (sum)])
(列 "把陣列攤開當參數" "(+ ;[1 2 3])" (+ ;[1 2 3]))
(defn greet [n &opt g] (default g "hi") (string g " " n))
(列 "void greet(n, g = \"hi\")" "&opt + default" [(greet "a") (greet "a" "yo")])
(def next-id (do (var n 0) (fn [] (++ n))))
(列 "static int n; return ++n;" "(do (var n 0) (fn [] (++ n)))" [(next-id) (next-id) (next-id)])

(節 "assert 與型別")
(列 "assert(1 == 2 && \"msg\")" "(assert (= 1 2) \"1 應該等於 2\")" (錯 |(assert (= 1 2) "1 應該等於 2")))
(列 "assert(x) 成立時" "(assert 42)  回那個值" (assert 42))
(列 "sizeof(int)" "(ffi/size :int)" (ffi/size :int))
(列 "元素個數" "(length @[1 2 3])" (length @[1 2 3]))
(列 "typeof" "(type 1) (type \"a\") (type @[])" [(type 1) (type "a") (type @[])])
(列 "atoi(\"12\") / atoi(\"x\")" "(scan-number …)  失敗給 nil" [(scan-number "12") (scan-number "x")])

(節 "argv 與 exit code（本支不 exit，只看 argv）")
(列 "argv" "(dyn *args*)" (dyn *args*))
(print "  exit code：(os/exit n)；沒叫就是 0，沒攔到的 error 是 1")
(print "\n✓ compare-c 跑完——main／stdin／stderr 的實測見 docs/43c")
